### ISSUE TITLE
Textareas

### ISSUE THREAD

**Issue by Mement0o** [vincent-peugnet/wcms#112] opened 2020-05-07 18:48 UTC
Heey there is still these good old textarea thing that breaks the editor.

![aie](https://user-images.githubusercontent.com/40144264/81332263-108d8300-90a3-11ea-8501-43b1ef8a3caa.png)

when I write <textarea></textarea> in the editor i have to get the content of the page with the inspector modify it and create a new article  to get the page back on traxx. When downloading the json and creating a newpage it breaks the page instantly.

**Comment by n-peugnet** [comment] 2020-05-08 10:03
I cannot reproduce. @Mement0o could you give me a step by step how to reproduce this bug with exactly what to type ? Ideally in an empty page.

**Comment by n-peugnet** [comment] 2020-05-08 10:13
On chrome and firefox I have a different bug, it does not break the layout of the page but the closing tag `</textarea>` is not saved. It must be an escaping problem

**Closed** 2020-05-08 10:50 UTC
Labels: help wanted
