### ISSUE TITLE
Diff beetwen Publishing and Updating datas / autosave

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#56] opened 2020-02-04 22:12 UTC

**Comment by n-peugnet** [comment] 2020-04-09 12:23
Isn't it a duplicate of #78 ?

**Comment by vincent-peugnet** [comment] 2020-04-09 18:18
Yeah kind of, it was an ancient idea actually : to ask for merging if there where changes made by another editor tab between opening current editor and click update.

**Comment by n-peugnet** [comment] 2020-04-28 16:32
Duplicate of #78

**Closed** 2020-04-28 16:33 UTC
Labels: enhancement, refactoring
